const BASE = import.meta.env.BASE_URL;

export const projectsData = [
  {
    id: 'kifisia',
    title: { en: 'Kifisia', el: 'Κηφισιά' },
    folder: 'kifisia',
    bgColor: '#ffffff',
    textColor: '#eccbb7',
    description: {
      en: 'An exclusive residential project in Kifisia. We integrated premium natural oak materials with bespoke minimalist lighting fixtures to create an airy, sophisticated environment, fulfilling the client’s desire for modern elegance.',
      el: 'Ένα αποκλειστικό οικιστικό έργο στην Κηφισιά. Ενσωματώσαμε υλικά από φυσικό δρυ με μινιμαλιστικά φωτιστικά κατά παραγγελία για να δημιουργήσουμε ένα αέρινο, εκλεπτυσμένο περιβάλλον, εκπληρώνοντας την επιθυμία του πελάτη για μοντέρνα κομψότητα.'
    },
    images: [
      BASE + 'projects/kifisia/kifisia1.jpg',
      BASE + 'projects/kifisia/kifisia10.png',
      BASE + 'projects/kifisia/kifisia11.jpg',
      BASE + 'projects/kifisia/kifisia12.png',
      BASE + 'projects/kifisia/kifisia13.jpg',
      BASE + 'projects/kifisia/kifisia14.png',
      BASE + 'projects/kifisia/kifisia15.jpg',
      BASE + 'projects/kifisia/kifisia16.png',
      BASE + 'projects/kifisia/kifisia17.jpg',
      BASE + 'projects/kifisia/kifisia18.png',
      BASE + 'projects/kifisia/kifisia19.jpg',
      BASE + 'projects/kifisia/kifisia2.png',
      BASE + 'projects/kifisia/kifisia20.png',
      BASE + 'projects/kifisia/kifisia21.jpg',
      BASE + 'projects/kifisia/kifisia22.png',
      BASE + 'projects/kifisia/kifisia23.jpg',
      BASE + 'projects/kifisia/kifisia3.jpg',
      BASE + 'projects/kifisia/kifisia4.png',
      BASE + 'projects/kifisia/kifisia5.jpg',
      BASE + 'projects/kifisia/kifisia6.png',
      BASE + 'projects/kifisia/kifisia7.jpg',
      BASE + 'projects/kifisia/kifisia8.png',
      BASE + 'projects/kifisia/kifisia9.jpg'
    ]
  },
  {
    id: 'thessaloniki-city-center',
    title: { en: 'Thessaloniki City Center', el: 'Κέντρο Θεσσαλονίκης' },
    folder: 'skgcenter',
    bgColor: '#eccbb7',
    textColor: '#ffffff',
    description: {
      en: 'A dynamic transformation of a historical apartment in Thessaloniki City Center. By knocking down unnecessary partitions and introducing industrial steel accents against exposed brick, we revitalized the urban layout for a young professional.',
      el: 'Μια δυναμική μεταμόρφωση ενός ιστορικού διαμερίσματος στο Κέντρο της Θεσσαλονίκης. Καταρρίπτοντας περιττά χωρίσματα και εισάγοντας βιομηχανικές ατσάλινες λεπτομέρειες σε συνδυασμό με εμφανές τούβλο, αναζωογονήσαμε την αστική διαρρύθμιση για έναν νέο επαγγελματία.'
    },
    images: [
      BASE + 'projects/skgcenter/skgcenter1.png',
      BASE + 'projects/skgcenter/skgcenter10.png',
      BASE + 'projects/skgcenter/skgcenter11.png',
      BASE + 'projects/skgcenter/skgcenter12.png',
      BASE + 'projects/skgcenter/skgcenter13.png',
      BASE + 'projects/skgcenter/skgcenter14.png',
      BASE + 'projects/skgcenter/skgcenter15.png',
      BASE + 'projects/skgcenter/skgcenter16.png',
      BASE + 'projects/skgcenter/skgcenter17.png',
      BASE + 'projects/skgcenter/skgcenter18.png',
      BASE + 'projects/skgcenter/skgcenter19.png',
      BASE + 'projects/skgcenter/skgcenter2.png',
      BASE + 'projects/skgcenter/skgcenter20.png',
      BASE + 'projects/skgcenter/skgcenter21.png',
      BASE + 'projects/skgcenter/skgcenter22.png',
      BASE + 'projects/skgcenter/skgcenter3.png',
      BASE + 'projects/skgcenter/skgcenter4.png',
      BASE + 'projects/skgcenter/skgcenter5.png',
      BASE + 'projects/skgcenter/skgcenter6.png',
      BASE + 'projects/skgcenter/skgcenter7.png',
      BASE + 'projects/skgcenter/skgcenter8.png',
      BASE + 'projects/skgcenter/skgcenter9.png'
    ]
  },
  {
    id: 'tsimiski-street',
    title: { en: 'Tsimiski Street', el: 'Οδός Τσιμισκή' },
    folder: 'tsimiski',
    bgColor: '#ffffff',
    textColor: '#eccbb7',
    description: {
      en: 'A high-end retail and showroom space on Tsimiski Street. Our approach utilized seamless acoustic panels, hidden LED strip lighting, and monolithic marble counters to emphasize the brand’s minimalist ethos and premium product line.',
      el: 'Ένας υψηλής αισθητικής εμπορικός και εκθεσιακός χώρος στην Οδό Τσιμισκή. Η προσέγγισή μας χρησιμοποίησε ακουστικά πάνελ χωρίς ραφές, κρυφό φωτισμό LED και μονολιθικούς πάγκους από μάρμαρο για να τονίσει τη μινιμαλιστική φιλοσοφία και την premium σειρά προϊόντων του brand.'
    },
    images: [
      BASE + 'projects/tsimiski/tsimiski1.jpg',
      BASE + 'projects/tsimiski/tsimiski10.png',
      BASE + 'projects/tsimiski/tsimiski11.jpeg',
      BASE + 'projects/tsimiski/tsimiski12.jpeg',
      BASE + 'projects/tsimiski/tsimiski2.png',
      BASE + 'projects/tsimiski/tsimiski3.jpg',
      BASE + 'projects/tsimiski/tsimiski4.png',
      BASE + 'projects/tsimiski/tsimiski5.jpg',
      BASE + 'projects/tsimiski/tsimiski6.jpg',
      BASE + 'projects/tsimiski/tsimiski7.jpg',
      BASE + 'projects/tsimiski/tsimiski8.jpg',
      BASE + 'projects/tsimiski/tsimiski9.png'
    ]
  },
  {
    id: 'ekali',
    title: { en: 'Ekali', el: 'Εκάλη' },
    folder: 'ekali',
    bgColor: '#eccbb7',
    textColor: '#ffffff',
    description: {
      en: 'A luxurious villa retreat in Ekali. The design seamlessly connects indoor and outdoor living spaces through expansive glass facades. We recommended earthy travertine floors and warm walnut cabinetry to ground the vast, open volumes.',
      el: 'Ένα πολυτελές καταφύγιο (βίλα) στην Εκάλη. Ο σχεδιασμός συνδέει αρμονικά τους εσωτερικούς και εξωτερικούς χώρους διαβίωσης μέσα από μεγάλες γυάλινες όψεις. Προτείναμε γήινα δάπεδα από τραβερτίνη και ζεστά ντουλάπια από καρυδιά για να ισορροπήσουμε τους τεράστιους, ανοιχτούς όγκους.'
    },
    images: [
      BASE + 'projects/ekali/ekali1.png',
      BASE + 'projects/ekali/ekali10.png',
      BASE + 'projects/ekali/ekali11.png',
      BASE + 'projects/ekali/ekali12.png',
      BASE + 'projects/ekali/ekali13.png',
      BASE + 'projects/ekali/ekali14.png',
      BASE + 'projects/ekali/ekali15.png',
      BASE + 'projects/ekali/ekali16.png',
      BASE + 'projects/ekali/ekali2.png',
      BASE + 'projects/ekali/ekali3.png',
      BASE + 'projects/ekali/ekali4.png',
      BASE + 'projects/ekali/ekali5.png',
      BASE + 'projects/ekali/ekali6.png',
      BASE + 'projects/ekali/ekali7.png',
      BASE + 'projects/ekali/ekali8.png',
      BASE + 'projects/ekali/ekali9.png'
    ]
  },
  {
    id: 'karpenisi',
    title: { en: 'Karpenisi', el: 'Καρπενήσι' },
    folder: 'karpenisi',
    bgColor: '#ffffff',
    textColor: '#eccbb7',
    description: {
      en: 'A cozy winter chalet nestled in Karpenisi. We focused on thermal comfort and rustic warmth by proposing heavy timber beams, locally sourced stone cladding, and plush textiles, creating an inviting sanctuary amidst the snowy landscape.',
      el: 'Ένα ζεστό χειμερινό σαλέ φωλιασμένο στο Καρπενήσι. Επικεντρωθήκαμε στη θερμική άνεση και τη ρουστίκ ζεστασιά προτείνοντας βαριά ξύλινα δοκάρια, επενδύσεις από τοπική πέτρα και πλούσια υφάσματα, δημιουργώντας ένα φιλόξενο καταφύγιο μέσα στο χιονισμένο τοπίο.'
    },
    images: [
      BASE + 'projects/karpenisi/karpenisi1.jpg',
      BASE + 'projects/karpenisi/karpenisi10.png',
      BASE + 'projects/karpenisi/karpenisi11.jpg',
      BASE + 'projects/karpenisi/karpenisi12.png',
      BASE + 'projects/karpenisi/karpenisi13.jpg',
      BASE + 'projects/karpenisi/karpenisi14.png',
      BASE + 'projects/karpenisi/karpenisi15.jpg',
      BASE + 'projects/karpenisi/karpenisi16.png',
      BASE + 'projects/karpenisi/karpenisi17.jpg',
      BASE + 'projects/karpenisi/karpenisi18.png',
      BASE + 'projects/karpenisi/karpenisi19.jpg',
      BASE + 'projects/karpenisi/karpenisi2.jpg',
      BASE + 'projects/karpenisi/karpenisi20.png',
      BASE + 'projects/karpenisi/karpenisi21.jpg',
      BASE + 'projects/karpenisi/karpenisi22.jpg',
      BASE + 'projects/karpenisi/karpenisi23.jpg',
      BASE + 'projects/karpenisi/karpenisi24.jpg',
      BASE + 'projects/karpenisi/karpenisi25.jpg',
      BASE + 'projects/karpenisi/karpenisi26.jpg',
      BASE + 'projects/karpenisi/karpenisi27.jpg',
      BASE + 'projects/karpenisi/karpenisi28.jpg',
      BASE + 'projects/karpenisi/karpenisi29.jpg',
      BASE + 'projects/karpenisi/karpenisi3.jpg',
      BASE + 'projects/karpenisi/karpenisi30.jpg',
      BASE + 'projects/karpenisi/karpenisi31.jpg',
      BASE + 'projects/karpenisi/karpenisi32.jpg',
      BASE + 'projects/karpenisi/karpenisi33.jpg',
      BASE + 'projects/karpenisi/karpenisi34.jpg',
      BASE + 'projects/karpenisi/karpenisi35.jpg',
      BASE + 'projects/karpenisi/karpenisi36.jpg',
      BASE + 'projects/karpenisi/karpenisi37.jpg',
      BASE + 'projects/karpenisi/karpenisi38.jpg',
      BASE + 'projects/karpenisi/karpenisi4.jpg',
      BASE + 'projects/karpenisi/karpenisi5.jpg',
      BASE + 'projects/karpenisi/karpenisi6.jpg',
      BASE + 'projects/karpenisi/karpenisi7.png',
      BASE + 'projects/karpenisi/karpenisi8.png',
      BASE + 'projects/karpenisi/karpenisi9.jpg'
    ]
  }
];
